global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'task-services'
    static_configs:
      - targets: ['task-service-1:3001', 'task-service-2:3001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 